/**
 * Centralized React Query cache keys for every data source.
 * Use these instead of inline string arrays to keep invalidation consistent.
 */
export const queryKeys = {
  todos: ['todos'] as const,
  missions: ['missions'] as const,
  agents: ['agents'] as const,
  calendar: ['calendar'] as const,
  status: ['agent-status'] as const,
  prefs: ['prefs'] as const,
  authUser: ['auth-user'] as const,
  emails: (accountId?: string) => ['emails', accountId] as const,
  emailAccounts: ['email-accounts'] as const,
  search: (q: string) => ['search', q] as const,
  capture: ['capture'] as const,
  knowledge: ['knowledge'] as const,
  memory: ['workspace-files'] as const,
  ideas: (status?: string) => ['ideas', status] as const,
  missionEvents: (id: string) => ['mission-events', id] as const,
  chatHistory: ['chat', 'history'] as const,
  chatModels: ['chat', 'models'] as const,
  crons: ['crons'] as const,
  subagentsActive: ['subagents', 'active'] as const,
  agentCache: ['agent-cache'] as const,
  connections: ['status', 'connections'] as const,
  tailscalePeers: ['status', 'tailscale'] as const,
  health: ['status', 'health'] as const,
  secrets: {
    list: () => ['secrets'] as const,
    detail: (service: string) => ['secrets', service] as const,
  },
  bjornModules: ['bjorn', 'modules'] as const,
  bjornVersions: (id: string) => ['bjorn', 'versions', id] as const,
  openclawUsage: ['openclaw', 'usage'] as const,
  openclawModels: ['openclaw', 'models'] as const,
  openclawTools: ['openclaw', 'tools'] as const,
  openclawSkills: ['openclaw', 'skills'] as const,
  claudeSessions: ['claude-sessions'] as const,
  claudeSessionDetail: (id: string) => ['claude-sessions', id] as const,
  claudeSessionStatus: ['claude-sessions', 'status'] as const,
  gatewayStatus: ['gateway', 'status'] as const,
  gatewaySessions: ['gateway', 'sessions'] as const,
  sessionHistory: (id: string) => ['session-history', id] as const,
  vncStatus: ['vnc', 'status'] as const,
  approvals: ['approvals'] as const,
} as const
